### ISSUE TITLE
2ac22cfc9f114eb40b9a6406c6816bd4ba732cf0 broke OpenBSD build

### ISSUE THREAD

**Issue by jungle-boogie** [jarun/nnn#361]
[x] Operating System:
`OpenBSD -current`

[x] Desktop Environment:
`cwm`

[x] Terminal Emulator:
`xterm via tilda`

[x] Shell:
`ksh`

[x] Custom desktop opener (if applicable):
none

[ ] Issue exists on `nnn` master

```
$ git bisect log
git bisect start
# good: [06ff2c55da3d2ce110c91f0ca344ac7e58b25914] Remove -Wno-unused-parameter and do cleanup (#357)
git bisect good 06ff2c55da3d2ce110c91f0ca344ac7e58b25914
# good: [ab0fe6c408656718a3a27380648552828c2d0143] unmount() ask for target if not found (#358)
git bisect good ab0fe6c408656718a3a27380648552828c2d0143
# bad: [2ac22cfc9f114eb40b9a6406c6816bd4ba732cf0] Mouseclicks are no longer delayed (#353)
git bisect bad 2ac22cfc9f114eb40b9a6406c6816bd4ba732cf0
```
```
$ git checkout 2ac22cfc9f114eb40b9a6406c6816bd4ba732cf0
Previous HEAD position was 49bee69 suedit plugin (#359)
HEAD is now at 2ac22cf Mouseclicks are no longer delayed (#353)
```

```
$ gmake CC=clang
clang  -Wall -Wextra -O3   -o nnn src/nnn.c -lreadline -lncurses
src/nnn.c:3741:19: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
                                clock_gettime(CLOCK_MONOTONIC_RAW, &mousetimings[currentmouse]);
                                              ^
1 error generated.
gmake: *** [Makefile:68: nnn] Error 1
```

```
$ gmake -v
GNU Make 4.2.1
```

```
$ cc -v
OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
Target: amd64-unknown-openbsd6.6
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by jungle-boogie** [comment]
OpenBSD manpage for clock_gettime (2)
https://man.openbsd.org/clock_gettime

**Comment by sjmulder** [comment]
I came across this issue too in my SmartOS port. Commit 6a6b30d in PR #363 should fix it.

**Comment by jarun** [comment]
Fixed in PR #363.

**Comment by jungle-boogie** [comment]
Verified fixed in commit 522626a88dffb820cc14be707ce0e6940df42e88

**Comment by jungle-boogie** [comment]
Thanks for fixing, @sjmulder. By the way, 6.6 release is very soon.
