### ISSUE TITLE
Build error: `mach_gettime.h:5:10: fatal error: sys/_types/_timespec.h: No such file or directory`

### ISSUE THREAD

**Issue by barracuda156** [jarun/nnn#1920]
```
--->  Building nnn
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/nnn-4.9" && /usr/bin/make -j6 -w all CFLAGS_OPTIMIZATION="" O_PCRE=1 CC="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cc/opt/local/bin/gcc-mp-14" CXX="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cxx/opt/local/bin/g++-mp-14" OBJC="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/objc/opt/local/bin/gcc-mp-14" OBJCXX="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/objcxx/opt/local/bin/g++-mp-14" FC="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/fc/opt/local/bin/gfortran-mp-14" F77="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/f77/opt/local/bin/gfortran-mp-14" F90="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/f90/opt/local/bin/gfortran-mp-14" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/nnn-4.9'
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cc/opt/local/bin/gcc-mp-14 -I/opt/local/include -I/opt/local/include/LegacySupport -DPCRE -DMACOS_BELOW_1012 -Os -I/opt/local/include/LegacySupport -arch ppc -std=c11 -Wall -Wextra -Wshadow  -D_DARWIN_C_SOURCE -DNCURSES_WIDECHAR -L/opt/local/lib -Wl,-headerpad_max_install_names -lMacportsLegacySupport -arch ppc -o nnn misc/macos-legacy/mach_gettime.c src/nnn.c -lreadline -lpcre -L/opt/local/lib -Wl,-search_paths_first -lncurses -lpthread
In file included from misc/macos-legacy/mach_gettime.c:1:
misc/macos-legacy/mach_gettime.h:5:10: fatal error: sys/_types/_timespec.h: No such file or directory
    5 | #include <sys/_types/_timespec.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/nnn.c:112:
src/../misc/macos-legacy/mach_gettime.h:5:10: fatal error: sys/_types/_timespec.h: No such file or directory
    5 | #include <sys/_types/_timespec.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [nnn] Error 1
```

Generally, nothing of underscore headers are to be used from user side code. Those are headers which are pulled in where needed by the OS.
`/usr/include/sys/_types` does not exist on some versions of macOS.

**Comment by barracuda156** [comment]
`struct timespec` is defined in `/usr/include/sys/_structs.h`, which is included by `sys/stat.h`.

**Comment by jarun** [comment]
Can you please check where this was introduced?

**Comment by jarun** [comment]
Closing as it looks like a local issue and there is no response.
If you have a fix, please raise the PR directly.

**Comment by barracuda156** [comment]
@jarun Well, including a non-existing header cannot be a “local issue”, this has obviously nothing to do with MacPorts.
Also, you have tagged another developer, so I was waiting for a response from his side.

**Comment by jarun** [comment]
I am not sure why anyone else is not seeing this in years.
Anyway, since you are able to repro this, please raise a PR with the fix.

**Comment by jarun** [comment]
Also, I did ask you a question before tagging the dev, but there was no response. So my take was you are not following this actively.

**Comment by N-R-K** [comment]
> `struct timespec` is defined in `/usr/include/sys/_structs.h`, which is included by `sys/stat.h`.

The proper location for `struct timespec` according to POSIX should be `<sys/time.h>`. Can you change to it and see if that works?

**Comment by barracuda156** [comment]
> I am not sure why anyone else is not seeing this in years.

Perhaps because either no one tried to build it on earlier macOS or, more likely, whoever tried – got an error and did not report it.
Someone told me this fails to build, then I tried locally and got the same result (which kinda illustrates the point that potential users may not report failures to the upstream, unfortunately).

**Comment by barracuda156** [comment]
@N-R-K Yes, that also works, since `sys/time.h` includes `sys/_structs.h`:
https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.6.sdk/usr/include/sys/time.h#L77
https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.8.sdk/usr/include/sys/time.h#L78

Which has the define itself: https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.6.sdk/usr/include/sys/_structs.h#L86-L93

So on 10.8.5, for example, with original (non-existing) header build fails immediately on:
```
--->  Building nnn
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/nnn-4.9" && /usr/bin/make -j4 -w all CFLAGS_OPTIMIZATION="" O_PCRE=1 CC="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cc/usr/bin/clang" CXX="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cxx/usr/bin/clang++" OBJC="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/objc/usr/bin/clang" OBJCXX="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/objcxx/usr/bin/clang++" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/nnn-4.9'
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cc/usr/bin/clang -I/opt/local/include -DPCRE -DMACOS_BELOW_1012 -Os -arch x86_64 -arch i386 -std=c11 -Wall -Wextra -Wshadow  -D_DARWIN_C_SOURCE -DNCURSES_WIDECHAR -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -arch i386 -o nnn misc/macos-legacy/mach_gettime.c src/nnn.c -lreadline -lpcre -L/opt/local/lib -Wl,-search_paths_first -lncurses -lpthread
In file included from misc/macos-legacy/mach_gettime.c:1:
misc/macos-legacy/mach_gettime.h:5:10: fatal error: 'sys/_types/_timespec.h' file not found
#include <sys/_types/_timespec.h>
         ^
1 error generated.
In file included from src/nnn.c:112:
src/../misc/macos-legacy/mach_gettime.h:5:10: fatal error: 'sys/_types/_timespec.h' file not found
#include <sys/_types/_timespec.h>
         ^
1 error generated.
make: *** [nnn] Error 1
```
While if I replace it with `sys/time.h`, that error is gone. Unfortunately, on its own it is not sufficient, since then there are other errors, but the change looks correct (and, perhaps, you suggestion is better).
```
--->  Building nnn
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/nnn-4.9" && /usr/bin/make -j4 -w all CFLAGS_OPTIMIZATION="" O_PCRE=1 CC="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cc/usr/bin/clang" CXX="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cxx/usr/bin/clang++" OBJC="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/objc/usr/bin/clang" OBJCXX="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/objcxx/usr/bin/clang++" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/nnn-4.9'
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_nnn/nnn/work/compwrap/cc/usr/bin/clang -I/opt/local/include -DPCRE -DMACOS_BELOW_1012 -Os -arch x86_64 -arch i386 -std=c11 -Wall -Wextra -Wshadow  -D_DARWIN_C_SOURCE -DNCURSES_WIDECHAR -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -arch i386 -o nnn misc/macos-legacy/mach_gettime.c src/nnn.c -lreadline -lpcre -L/opt/local/lib -Wl,-search_paths_first -lncurses -lpthread
src/nnn.c:425:9: error: use of undeclared identifier 'max_align_t'
alignas(max_align_t) static context g_ctx[CTX_MAX];
        ^
src/nnn.c:507:9: error: use of undeclared identifier 'max_align_t'
alignas(max_align_t) static char g_buf[CMD_LEN_MAX];
        ^
src/nnn.c:510:9: error: use of undeclared identifier 'max_align_t'
alignas(max_align_t) static char g_sel[PATH_MAX];
        ^
src/nnn.c:513:9: error: use of undeclared identifier 'max_align_t'
alignas(max_align_t) static char g_tmpfpath[TMP_LEN_MAX];
        ^
src/nnn.c:516:9: error: use of undeclared identifier 'max_align_t'
alignas(max_align_t) static char g_pipepath[TMP_LEN_MAX];
        ^
src/nnn.c:2911:10: error: use of undeclared identifier 'max_align_t'
        alignas(max_align_t) static const int8_t result_type[] = {
                ^
src/nnn.c:3191:50: warning: missing field 'filter' initializer [-Wmissing-field-initializers]
                        struct kevent event_data[NUM_EVENT_SLOTS] = {0};
                                                                      ^
src/nnn.c:3191:49: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                        struct kevent event_data[NUM_EVENT_SLOTS] = {0};
                                                                     ^
                                                                     {}
src/nnn.c:3344:10: error: use of undeclared identifier 'max_align_t'
        alignas(max_align_t) wchar_t wln[REGEX_MAX];
                ^
src/nnn.c:4316:30: warning: missing field 'pathln' initializer [-Wmissing-field-initializers]
        session_header_t header = {0};
                                    ^
src/nnn.c:5714:7: warning: implicit declaration of function 'fstatat' is invalid in C99 [-Wimplicit-function-declaration]
                if (fstatat(fd, path, &sb_path, 0) == -1)
                    ^
src/nnn.c:5749:11: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'
                flags = AT_SYMLINK_NOFOLLOW;
                        ^
src/nnn.c:5763:32: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'
                        if (fstatat(fd, namep, &sb, AT_SYMLINK_NOFOLLOW) == -1)
                                                    ^
src/nnn.c:5785:42: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'
                        if (flags || (fstatat(fd, namep, &sb, AT_SYMLINK_NOFOLLOW) == -1)) {
                                                              ^
src/nnn.c:6729:10: error: use of undeclared identifier 'max_align_t'
        alignas(max_align_t) char newpath[PATH_MAX];
                ^
src/nnn.c:6730:10: error: use of undeclared identifier 'max_align_t'
        alignas(max_align_t) char runfile[NAME_MAX + 1];
                ^
src/nnn.c:6741:19: warning: missing field 'x' initializer [-Wmissing-field-initializers]
        MEVENT event = {0};
                         ^
5 warnings and 12 errors generated.
make: *** [nnn] Error 1
```

P. S. In MacPorts we use `legacysupport` library to provide all missing stuff, but there I have to disable `macos-legacy` component, since its definitions conflict with Apple ones which `legacysupport` uses. We have `nnn` working almost across the board in result: https://ports.macports.org/port/nnn/details (10.8–10.9 builds fail perhaps due to their system clang being too old, we need to switch them to a newer one – 10.6 uses either clang-11 or gcc14, both work fine; 10.5 failure is fake, there is just no working buildbot – in reality `nnn` builds and works on 10.5 ppc now).

**Comment by N-R-K** [comment]
`max_align_t` is a standard C11 type and `fstatat` is a standard POSIX function. If your platform/compiler/stdlib doesn't have these then you should upgrade to a newer version.

Otherwise you can raise a pull request with the required changes. None of the nnn devs use macos and so most mac related code has been contributed by outside contributors.

**Comment by barracuda156** [comment]
@N-R-K I guess for now we could fix the header, using your suggestion. I can make a PR for that.

Not sure I will fix everything to work without legacysupport (so after all who needs this on earlier macOS can just install `nnn` from MacPorts), but I will take a look at what is needed.

Clang error on 10.8 can be ignored, this is a compiler issue, not the OS or `nnn` issue. It should be fixed by switching compiler from Xcode to LLVM clang. That I can handle in MacPorts.
