### ISSUE TITLE
Build failed on Haiku

### ISSUE THREAD

**Issue by sikmir** [jarun/nnn#1448]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Haiku
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

```
$ haikuporter -S nnn-4.6
...
src/nnn.c:5445:9: error: unknown type name 'FTS'
 5445 |         FTS *tree = fts_open(path, FTS_PHYSICAL | FTS_XDEV | FTS_NOCHDIR, 0);
      |         ^~~
src/nnn.c:5445:21: warning: implicit declaration of function 'fts_open' [-Wimplicit-function-declaration]
 5445 |         FTS *tree = fts_open(path, FTS_PHYSICAL | FTS_XDEV | FTS_NOCHDIR, 0);
      |                     ^~~~~~~~
src/nnn.c:5445:36: error: 'FTS_PHYSICAL' undeclared (first use in this function)
 5445 |         FTS *tree = fts_open(path, FTS_PHYSICAL | FTS_XDEV | FTS_NOCHDIR, 0);
      |                                    ^~~~~~~~~~~~
src/nnn.c:5445:36: note: each undeclared identifier is reported only once for each function it appears in
src/nnn.c:5445:51: error: 'FTS_XDEV' undeclared (first use in this function)
 5445 |         FTS *tree = fts_open(path, FTS_PHYSICAL | FTS_XDEV | FTS_NOCHDIR, 0);
      |                                                   ^~~~~~~~
src/nnn.c:5445:62: error: 'FTS_NOCHDIR' undeclared (first use in this function); did you mean 'FTW_CHDIR'?
 5445 |         FTS *tree = fts_open(path, FTS_PHYSICAL | FTS_XDEV | FTS_NOCHDIR, 0);
      |                                                              ^~~~~~~~~~~
      |                                                              FTW_CHDIR
src/nnn.c:5446:9: error: unknown type name 'FTSENT'
 5446 |         FTSENT *node;
      |         ^~~~~~
src/nnn.c:5448:24: warning: implicit declaration of function 'fts_read'; did you mean 'fread'? [-Wimplicit-function-declaration]
 5448 |         while ((node = fts_read(tree))) {
      |                        ^~~~~~~~
      |                        fread
src/nnn.c:5448:22: warning: assignment to 'int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 5448 |         while ((node = fts_read(tree))) {
      |                      ^
src/nnn.c:5449:25: error: request for member 'fts_info' in something not a structure or union
 5449 |                 if (node->fts_info & FTS_D) {
      |                         ^~
src/nnn.c:5449:38: error: 'FTS_D' undeclared (first use in this function); did you mean 'FTW_D'?
 5449 |                 if (node->fts_info & FTS_D) {
      |                                      ^~~~~
      |                                      FTW_D
src/nnn.c:5455:26: error: request for member 'fts_statp' in something not a structure or union
 5455 |                 sb = node->fts_statp;
      |                          ^~
src/nnn.c:465:24: error: request for member 'fts_info' in something not a structure or union
  465 | #define DU_TEST (((node->fts_info & FTS_F) && \
      |                        ^~
src/nnn.c:5458:44: note: in expansion of macro 'DU_TEST'
 5458 |                         if (sb->st_size && DU_TEST)
      |                                            ^~~~~~~
src/nnn.c:465:37: error: 'FTS_F' undeclared (first use in this function); did you mean 'FTW_F'?
  465 | #define DU_TEST (((node->fts_info & FTS_F) && \
      |                                     ^~~~~
src/nnn.c:5458:44: note: in expansion of macro 'DU_TEST'
 5458 |                         if (sb->st_size && DU_TEST)
      |                                            ^~~~~~~
src/nnn.c:466:81: error: request for member 'fts_info' in something not a structure or union
  466 |                 (sb->st_nlink <= 1 || test_set_bit((uint_t)sb->st_ino))) || node->fts_info & FTS_DP)
      |                                                                                 ^~
src/nnn.c:5458:44: note: in expansion of macro 'DU_TEST'
 5458 |                         if (sb->st_size && DU_TEST)
      |                                            ^~~~~~~
src/nnn.c:466:94: error: 'FTS_DP' undeclared (first use in this function); did you mean 'FTW_DP'?
  466 |                 (sb->st_nlink <= 1 || test_set_bit((uint_t)sb->st_ino))) || node->fts_info & FTS_DP)
      |                                                                                              ^~~~~~
src/nnn.c:5458:44: note: in expansion of macro 'DU_TEST'
 5458 |                         if (sb->st_size && DU_TEST)
      |                                            ^~~~~~~
src/nnn.c:465:24: error: request for member 'fts_info' in something not a structure or union
  465 | #define DU_TEST (((node->fts_info & FTS_F) && \
      |                        ^~
src/nnn.c:5460:45: note: in expansion of macro 'DU_TEST'
 5460 |                 } else if (sb->st_blocks && DU_TEST)
      |                                             ^~~~~~~
src/nnn.c:466:81: error: request for member 'fts_info' in something not a structure or union
  466 |                 (sb->st_nlink <= 1 || test_set_bit((uint_t)sb->st_ino))) || node->fts_info & FTS_DP)
      |                                                                                 ^~
src/nnn.c:5460:45: note: in expansion of macro 'DU_TEST'
 5460 |                 } else if (sb->st_blocks && DU_TEST)
      |                                             ^~~~~~~
src/nnn.c:5466:9: warning: implicit declaration of function 'fts_close'; did you mean 'fclose'? [-Wimplicit-function-declaration]
 5466 |         fts_close(tree);
      |         ^~~~~~~~~
      |         fclose
misc/haiku/Makefile:170: recipe for target 'nnn.o' failed
```

**Comment by sikmir** [comment]
Caused by https://github.com/jarun/nnn/commit/284a3c4866b77f0d452d91aaf026068dd1e44cb1

**Comment by jarun** [comment]
That change was done a year ago. I wonder if there are any `nnn` users on Haiku..

Please check how it;s possible to use the FTS library on Haiku. I see this - https://dev.haiku-os.org/ticket/9337

**Comment by jarun** [comment]
@CodeforEvolution you confirmed [here](https://github.com/jarun/nnn/issues/1022#issuecomment-848953023) that FTS is available on Haiku. Can you please help @sikmir with the compilation issues?

**Comment by CodeforEvolution** [comment]
Hey, here’s what happened:
https://git.haiku-os.org/haiku/commit/?id=0afb8a1b494ba36c5effd3430240b8e9439076c7

It looks like ftw and its parts were moved due to not being part of posix, and instead being bsd-specific extensions. I can look into providing a quick fix relatively soon.

**Comment by N-R-K** [comment]
> due to not being part of posix, and instead being bsd-specific extensions

I don't think that's correct. It's still defined in POSIX 2018 [^0]. It's marked obsolete, but doesn't mean that it *has been* removed, it means that it *might be* removed in the future.

[^0]: https://www.man7.org/linux/man-pages/man3/ftw.3p.html

**Comment by jarun** [comment]
Closing as this needs to be fixed on Haiku side. We are not going back to FTW.
